version: '3'
services:
  app:
    build: ./docker/php
    volumes:
      - ./app:/var/www/html
    ports:
      - 80:80
      - 443:443
    networks:
      app_net:
        ipv4_address: 172.30.0.4
  mariadb:
    build: ./docker/mariadb
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3307:3307
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      app_net:
        ipv4_address: 172.30.0.3
volumes:
  dbdata:
networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.30.0.0/24
